name: Generate Snake

on:
  schedule:
    - cron: "0 15 * * *" # 한국 시간 자정
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # 뱀의 이동 속도 설정 (기본값은 5, 숫자가 클수록 빠름)
          snake_speed: 20
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-snake-custom.svg?color_snake=#f44336&color_dots=#ebedf0,#ffeb3b,#ffc107,#ff9800,#f44336
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Separate Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: snake-assets # 뱃지와 같은 브랜치로 설정
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
